apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: nginx-
patches:
  - target:
      kind: Deployment
      name: deployment
    patch: |-
      - op: add
        path: /metadata/labels/tier
        value: web
      - op: add
        path: /spec/template/metadata/labels/tier
        value: web
  - target:
      kind: Service
      name: service
    patch: |-
      - op: add
        path: /metadata/labels/tier
        value: web
